### ISSUE TITLE
level in Sarif is undefined for object

### ISSUE THREAD

**Issue by Nold360** [GridexX/sarif-junit#1]
I'm using your project with mega-linter to convert sarif2junit. In my current test pipeline i've been running into this error message:

```
level in Sarif is undefined for object : {"locations":[{"physicalLocation":{"artifactLocation":{"uri":"ansible/playbook.yml","uriBaseId":"SRCROOT"},"region":{"startLine":1}}}],"message":{"text":"while parsing a block mapping\n  in \"<unicode string>\", line 1, column 3:\n    - name: My fancy playbook\n      ^\nexpected <block end>, but found '<block sequence start>'\n  in \"<unicode string>\", line 10, column 4:\n       - name: another task\n       ^"},"ruleId":"load-failure"}
```

The corrosponding sarif block seems to be: SEE NEXT COMMENT

Here is the full sarif report: https://pastebin.com/dbiXUreB

**Comment by Nold360** [comment]
maybe i interpreted the error wrong and it's complaining about this part:

```json
            "results": [
                {
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "ansible/playbook.yml",
                                    "uriBaseId": "SRCROOT"
                                },
                                "region": {
                                    "startLine": 1
                                }
                            }
                        }
                    ],
                    "message": {
                        "text": "while parsing a block mapping\n  in \"<unicode string>\", line 1, column 3:\n    - name: My fancy playbook\n      ^\nexpected <block end>, but found '<block sequence start>'\n  in \"<unicode string>\", line 10, column 4:\n       - name: another task\n       ^"
                    },
                    "ruleId": "load-failure"
                }
            ],
```

**Comment by Nold360** [comment]
Oh, i think i got it. Results are required to have a "level": https://github.com/GridexX/sarif-junit/blob/985b3018282815b3cd835642d77c55f91466aa5f/lib/parser.js#L26-L27

But according to the specification, it's not required: https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317648

**Comment by GridexX** [comment]
Hello @Nold360 !
Thanks you a lot for your feedback and using my tool!

Indeed, this tool was build for the `v2.0` specification where the level entry was mandatory.

I have updated the parser to allow empty `level` property. 

You could now try with the `1.1.4` version :  
```bash
npm install -g sarif-junit@1.1.4
//or for yarn
yarn global add sarif-junit@1.1.4
```

Thansk for your feedback and hope it will works for you! Don't hesitate to tell me if their are other issues.

Have a great day :smile:

**Comment by Nold360** [comment]
Thanks a lot for looking into this! 

I've wanted to give 1.14 a try, but it seems like it's not released yet: https://www.npmjs.com/package/sarif-junit

**Comment by GridexX** [comment]
Sorry, here is the new [package](https://www.npmjs.com/package/sarif-junit) @Nold360 

One question, how did you find this package and why are you using it ?

It was created for a GitLab jobs, if you want to check it out : https://r2devops.io/_/r2devops-bot/mega_linter

**Comment by Nold360** [comment]
Thanks it seems to work now 👍 

And yea, i think that's the project i stole the code from :D
